prettier changes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,31 +7,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v2
+      - name: Checkout Repository
+        uses: actions/checkout@v2
 
-    - name: Install Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: 18
+      - name: Install Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: 18
 
-    - name: Install Dependencies
-      run: npm install
+      - name: Install Dependencies
+        run: npm install
 
-    - name: Code Formatting Check #Runs Prettier Script
-      run: npm run prettier
+      - name: Code Formatting Check #Runs Prettier Script
+        run: npm run prettier
 
-    - name: Linting Check #Runs ESLint Script
-      run: npm run lint
+      - name: Linting Check #Runs ESLint Script
+        run: npm run lint
 
-    - name: Build #Build the project
-      run: npm run build
+      - name: Build #Build the project
+        run: npm run build
 
-    - name: Check Build Status
-      run: |
-        if [ $? -eq 0 ]; then
-          echo "Build successful!"
-        else
-          echo "Build failed!"
-          exit 1
-        fi
+      - name: Check Build Status
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Build successful!"
+          else
+            echo "Build failed!"
+            exit 1
+          fi
